services:
  vital:
    build: .
    container_name: vital
    restart: unless-stopped
    expose:
      - "8000"
    volumes:
      - ./exclusion_rules.json:/app/exclusion_rules.json:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
